//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PORTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calendar
    {
        public System.DateTime dt { get; set; }
        public Nullable<bool> isWeekday { get; set; }
        public Nullable<bool> isHoliday { get; set; }
        public Nullable<short> Y { get; set; }
        public Nullable<short> FY { get; set; }
        public Nullable<byte> Q { get; set; }
        public Nullable<byte> M { get; set; }
        public Nullable<byte> D { get; set; }
        public Nullable<byte> DW { get; set; }
        public string monthname { get; set; }
        public string dayname { get; set; }
        public Nullable<byte> W { get; set; }
        public Nullable<byte> UTCOffset { get; set; }
        public string HolidayDescription { get; set; }
        public Nullable<int> DaysLeftCount { get; set; }
        public Nullable<int> WorkingDay { get; set; }
    }
}
