//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PORTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANYPROJS
    {
        public long ProjCompanyID { get; set; }
        public long ProjectID { get; set; }
        public long CompanyID { get; set; }
        public bool IS_ACTIVE { get; set; }
    }
}
