//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PORTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANIES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMPANIES()
        {
            this.INSPECTIONREQS = new HashSet<INSPECTIONREQS>();
            this.PROJCOMPANIES = new HashSet<PROJCOMPANIES>();
        }
    
        public long COMPANYID { get; set; }
        public string COMPANYNAME { get; set; }
        public long COMPANYTYPEID { get; set; }
        public string ADDRESS { get; set; }
        public string ADDRESS2 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public Nullable<long> ZIP { get; set; }
        public Nullable<long> ZIP2 { get; set; }
        public string TELEPHONE { get; set; }
        public string EXTENSION { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public bool IS_ACTIVE { get; set; }
        public string ADDED_BY { get; set; }
        public System.DateTime ADDED_DT { get; set; }
        public string UPDATED_BY { get; set; }
        public System.DateTime UPDATED_DT { get; set; }
        public string CONTACTNAME { get; set; }
        public Nullable<bool> IS_BPPORTALADMIN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSPECTIONREQS> INSPECTIONREQS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJCOMPANIES> PROJCOMPANIES { get; set; }
        public virtual LOOKUP LOOKUP { get; set; }
    }
}
