//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PORTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONTACTS()
        {
            this.INSPECTIONREQS = new HashSet<INSPECTIONREQS>();
            this.EMAILRECIPIENTS = new HashSet<EMAILRECIPIENTS>();
            this.POCREQUEST = new HashSet<POCREQUEST>();
            this.PROJCONTACTS = new HashSet<PROJCONTACTS>();
            this.INSPECTIONREQS1 = new HashSet<INSPECTIONREQS>();
        }
    
        public long CONTACTID { get; set; }
        public long CONTACTTYPEID { get; set; }
        public string INTERNALUSERNAME { get; set; }
        public string CONTACTNAME { get; set; }
        public string CONTACTPHONE { get; set; }
        public string EXTENSION { get; set; }
        public string EMAIL { get; set; }
        public Nullable<long> COMPANYID { get; set; }
        public bool IS_ACTIVE { get; set; }
        public string ADDED_BY { get; set; }
        public System.DateTime ADDED_DT { get; set; }
        public string UPDATED_BY { get; set; }
        public System.DateTime UPDATED_DT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSPECTIONREQS> INSPECTIONREQS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMAILRECIPIENTS> EMAILRECIPIENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POCREQUEST> POCREQUEST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJCONTACTS> PROJCONTACTS { get; set; }
        public virtual LOOKUP LOOKUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSPECTIONREQS> INSPECTIONREQS1 { get; set; }
    }
}
