//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PORTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EASEMENTS
    {
        public long EASEMENTID { get; set; }
        public long PROJECTID { get; set; }
        public int EASEMENT_NUM { get; set; }
        public bool EASEMENT_REQUIRED { get; set; }
        public Nullable<System.DateTime> SURVEY_REVIEW { get; set; }
        public Nullable<System.DateTime> OK_FROM_SURVEY { get; set; }
        public Nullable<bool> EASEMENTS_MAP { get; set; }
        public Nullable<long> FINAL_MAP_PARCEL_MAP { get; set; }
        public Nullable<System.DateTime> MAP_SIGNED { get; set; }
        public Nullable<long> BOOKS { get; set; }
        public Nullable<long> PAGE { get; set; }
        public Nullable<System.DateTime> DOC_TO_ENG { get; set; }
        public Nullable<System.DateTime> EXEC_DOCS { get; set; }
        public Nullable<bool> DOCS_REC { get; set; }
        public string DOC_NUM { get; set; }
        public bool IS_ACTIVE { get; set; }
        public string ADDED_BY { get; set; }
        public System.DateTime ADDED_DT { get; set; }
        public string UPDATED_BY { get; set; }
        public System.DateTime UPDATED_DT { get; set; }
    }
}
