//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PORTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMAILS
    {
        public long EMAILID { get; set; }
        public long EMAILTYPEID { get; set; }
        public Nullable<long> SOURCEID { get; set; }
        public Nullable<long> PROJECTID { get; set; }
        public string CHARBODY { get; set; }
        public long USERID { get; set; }
        public bool EMAIL_SENT { get; set; }
        public bool DO_NOT_SEND_ON_ADDED { get; set; }
        public bool IS_ACTIVE { get; set; }
        public string ADDED_BY { get; set; }
        public System.DateTime ADDED_DT { get; set; }
    
        public virtual ACL ACL { get; set; }
        public virtual LOOKUP LOOKUP { get; set; }
        public virtual PROJECTS PROJECTS { get; set; }
    }
}
