//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PORTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMRIGHTS
    {
        public long FORMRIGHTSID { get; set; }
        public long ROLEID { get; set; }
        public long FORMID { get; set; }
        public long FORMRIGHTTYPEID { get; set; }
        public bool IS_ACTIVE { get; set; }
        public string ADDED_BY { get; set; }
        public System.DateTime ADDED_DT { get; set; }
        public string UPDATED_BY { get; set; }
        public System.DateTime UPDATED_DT { get; set; }
    
        public virtual FORMS FORMS { get; set; }
        public virtual ROLES ROLES { get; set; }
    }
}
