//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PORTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOLIDAYS
    {
        public int HOLIDAYID { get; set; }
        public System.DateTime HOLIDAYDATE { get; set; }
        public string DESCRIPTION { get; set; }
    }
}
