//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PORTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSPECTIONS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INSPECTIONS()
        {
            this.CERTSOFOCC = new HashSet<CERTSOFOCC>();
            this.INSPATTRIBS = new HashSet<INSPATTRIBS>();
            this.INSPCHAINOFCUSTODY = new HashSet<INSPCHAINOFCUSTODY>();
            this.INSPCHECKSHEET = new HashSet<INSPCHECKSHEET>();
            this.PROJOOOINSPS = new HashSet<PROJOOOINSPS>();
        }
    
        public long INSPECTIONID { get; set; }
        public bool IS_OOOINSP { get; set; }
        public long INSPECTIONSTATUSID { get; set; }
        public long INSPECTIONREQID { get; set; }
        public long INSPECTORID { get; set; }
        public long INSPECTIONTYPEID { get; set; }
        public long ASSETID { get; set; }
        public Nullable<System.DateTime> SCHED_DATE { get; set; }
        public Nullable<System.DateTime> COMPL_DATE { get; set; }
        public long DISPOSITIONID { get; set; }
        public bool IS_NOT_REQ { get; set; }
        public string EVALUATED_BY { get; set; }
        public Nullable<System.DateTime> EVALUATE_START_DT { get; set; }
        public Nullable<System.DateTime> EVALUATE_END_DT { get; set; }
        public Nullable<System.DateTime> EMAIL_SENT { get; set; }
        public Nullable<long> EMAILID { get; set; }
        public bool IS_ACTIVE { get; set; }
        public string ADDED_BY { get; set; }
        public System.DateTime ADDED_DT { get; set; }
        public string UPDATED_BY { get; set; }
        public System.DateTime UPDATED_DT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CERTSOFOCC> CERTSOFOCC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSPATTRIBS> INSPATTRIBS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSPCHAINOFCUSTODY> INSPCHAINOFCUSTODY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSPCHECKSHEET> INSPCHECKSHEET { get; set; }
        public virtual INSPECTIONREQS INSPECTIONREQS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJOOOINSPS> PROJOOOINSPS { get; set; }
        public virtual LOOKUP LOOKUP { get; set; }
        public virtual LOOKUP LOOKUP1 { get; set; }
        public virtual INSPECTORS INSPECTORS { get; set; }
        public virtual LOOKUP LOOKUP2 { get; set; }
    }
}
