//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PORTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSPCHECKSHEETTEMPLATE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INSPCHECKSHEETTEMPLATE()
        {
            this.INSPCHECKSHEET = new HashSet<INSPCHECKSHEET>();
            this.INSPCHECKSHEETATTRIBS = new HashSet<INSPCHECKSHEETATTRIBS>();
        }
    
        public long INSPCHECKSHEETTEMPLATEID { get; set; }
        public long INSPWORKFLOW_NUM { get; set; }
        public long TEMPLATE_NUM { get; set; }
        public bool IS_STANDARD_REQ { get; set; }
        public bool DISPLAY_TO_LEFT { get; set; }
        public bool MULTICHOICE_REQ { get; set; }
        public string DESCRIPTION { get; set; }
        public long DESCR_ORDER { get; set; }
        public bool IS_ACTIVE { get; set; }
        public string ADDED_BY { get; set; }
        public System.DateTime ADDED_DT { get; set; }
        public string UPDATED_BY { get; set; }
        public System.DateTime UPDATED_DT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSPCHECKSHEET> INSPCHECKSHEET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSPCHECKSHEETATTRIBS> INSPCHECKSHEETATTRIBS { get; set; }
    }
}
