//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PORTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSPECTIONREQS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INSPECTIONREQS()
        {
            this.INSPECTIONS = new HashSet<INSPECTIONS>();
        }
    
        public long INSPECTIONREQID { get; set; }
        public long REQUESTSTATUSID { get; set; }
        public long PROJECTID { get; set; }
        public System.DateTime REQUESTDATE { get; set; }
        public long CALLERID { get; set; }
        public long FIELDCONTACTID { get; set; }
        public long COMPANYID { get; set; }
        public System.DateTime FROM_DT { get; set; }
        public Nullable<System.DateTime> TO_DT { get; set; }
        public long WORK_SHIFT { get; set; }
        public Nullable<System.TimeSpan> OT_STARTTIME { get; set; }
        public bool IS_ACTIVE { get; set; }
        public string ADDED_BY { get; set; }
        public System.DateTime ADDED_DT { get; set; }
        public string UPDATED_BY { get; set; }
        public System.DateTime UPDATED_DT { get; set; }
    
        public virtual COMPANIES COMPANIES { get; set; }
        public virtual CONTACTS CONTACTS { get; set; }
        public virtual CONTACTS CONTACTS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSPECTIONS> INSPECTIONS { get; set; }
        public virtual PROJECTS PROJECTS { get; set; }
        public virtual LOOKUP LOOKUP { get; set; }
        public virtual LOOKUP LOOKUP1 { get; set; }
    }
}
