//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PORTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSPCHAINOFCUSTODY
    {
        public long ICofCID { get; set; }
        public long InspectionID { get; set; }
        public long CurrentLocationID { get; set; }
        public long ActionID { get; set; }
        public string TransferredBy { get; set; }
        public System.DateTime Transfer_DT { get; set; }
        public string TransferredByOnBehalfOf { get; set; }
        public string AssignedTo { get; set; }
        public bool IS_ACTIVE { get; set; }
        public string ADDED_BY { get; set; }
        public System.DateTime ADDED_DT { get; set; }
        public string UPDATED_BY { get; set; }
        public System.DateTime UPDATED_DT { get; set; }
    
        public virtual LOOKUP LOOKUP { get; set; }
        public virtual LOOKUP LOOKUP1 { get; set; }
        public virtual INSPECTIONS INSPECTIONS { get; set; }
    }
}
