//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PORTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOOKUP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOOKUP()
        {
            this.ABOUTCONTENT = new HashSet<ABOUTCONTENT>();
            this.ASSETATTRIBS = new HashSet<ASSETATTRIBS>();
            this.ATTACHMENTS = new HashSet<ATTACHMENTS>();
            this.CHECKSHEET = new HashSet<CHECKSHEET>();
            this.COMMENTS = new HashSet<COMMENTS>();
            this.COMPANIES = new HashSet<COMPANIES>();
            this.CONTACTLOOKUPS = new HashSet<CONTACTLOOKUPS>();
            this.CONTACTLOOKUPS1 = new HashSet<CONTACTLOOKUPS>();
            this.CONTACTS = new HashSet<CONTACTS>();
            this.EMAILGROUPS = new HashSet<EMAILGROUPS>();
            this.EMAILRECIPIENTS = new HashSet<EMAILRECIPIENTS>();
            this.EMAILRECIPIENTS1 = new HashSet<EMAILRECIPIENTS>();
            this.EMAILS = new HashSet<EMAILS>();
            this.INSPATTRIBS = new HashSet<INSPATTRIBS>();
            this.INSPCHAINOFCUSTODY = new HashSet<INSPCHAINOFCUSTODY>();
            this.INSPCHAINOFCUSTODY1 = new HashSet<INSPCHAINOFCUSTODY>();
            this.INSPCHECKSHEET = new HashSet<INSPCHECKSHEET>();
            this.INSPCHECKSHEETATTRIBS = new HashSet<INSPCHECKSHEETATTRIBS>();
            this.INSPECTIONREQS = new HashSet<INSPECTIONREQS>();
            this.INSPECTIONREQS1 = new HashSet<INSPECTIONREQS>();
            this.INSPECTIONS = new HashSet<INSPECTIONS>();
            this.INSPECTIONS1 = new HashSet<INSPECTIONS>();
            this.INSPECTIONS2 = new HashSet<INSPECTIONS>();
            this.INSPWORKFLOWS = new HashSet<INSPWORKFLOWS>();
            this.INSPWORKFLOWS1 = new HashSet<INSPWORKFLOWS>();
            this.PLANCHAINOFCUSTODY = new HashSet<PLANCHAINOFCUSTODY>();
            this.PLANREVIEWMETRICS = new HashSet<PLANREVIEWMETRICS>();
            this.PROJECTATTRIBLEVELS = new HashSet<PROJECTATTRIBLEVELS>();
            this.PROJECTATTRIBS = new HashSet<PROJECTATTRIBS>();
            this.PRIVINSPOBJS = new HashSet<PRIVINSPOBJS>();
            this.PLANTRANSFERWORKFLOW = new HashSet<PLANTRANSFERWORKFLOW>();
            this.PLANCHAINOFCUSTODY1 = new HashSet<PLANCHAINOFCUSTODY>();
            this.PROJINSPTEMPLATE = new HashSet<PROJINSPTEMPLATE>();
            this.PROJOOOINSPS = new HashSet<PROJOOOINSPS>();
            this.PROJECTATTRIBLEVELS1 = new HashSet<PROJECTATTRIBLEVELS>();
            this.PLANSUBMITTALS = new HashSet<PLANSUBMITTALS>();
            this.PLANTRANSFERWORKFLOW1 = new HashSet<PLANTRANSFERWORKFLOW>();
            this.PLANTRANSFERWORKFLOW2 = new HashSet<PLANTRANSFERWORKFLOW>();
            this.PROJMATERIALS = new HashSet<PROJMATERIALS>();
            this.PROJMATERIALS1 = new HashSet<PROJMATERIALS>();
            this.PROJMATERIALS2 = new HashSet<PROJMATERIALS>();
            this.PROJINSPASSETS = new HashSet<PROJINSPASSETS>();
            this.PROJECTS = new HashSet<PROJECTS>();
            this.PROJINSPINFO = new HashSet<PROJINSPINFO>();
            this.PROJINSPINFO1 = new HashSet<PROJINSPINFO>();
            this.PROJINSPINFO2 = new HashSet<PROJINSPINFO>();
            this.PROJINSPINFO3 = new HashSet<PROJINSPINFO>();
            this.PROJECTS1 = new HashSet<PROJECTS>();
            this.PROJECTS2 = new HashSet<PROJECTS>();
            this.PROJINSPINFO4 = new HashSet<PROJINSPINFO>();
            this.SEGMENTS = new HashSet<SEGMENTS>();
            this.PLANSUBMITTALS1 = new HashSet<PLANSUBMITTALS>();
            this.SEGMENTS1 = new HashSet<SEGMENTS>();
        }
    
        public long LOOKUPID { get; set; }
        public string FIELDTYPE { get; set; }
        public string VALUE { get; set; }
        public string DESCRIPTION { get; set; }
        public bool IS_ACTIVE { get; set; }
        public string ADDED_BY { get; set; }
        public System.DateTime ADDED_DT { get; set; }
        public string UPDATED_BY { get; set; }
        public System.DateTime UPDATED_DT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ABOUTCONTENT> ABOUTCONTENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSETATTRIBS> ASSETATTRIBS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATTACHMENTS> ATTACHMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHECKSHEET> CHECKSHEET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMENTS> COMMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPANIES> COMPANIES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTACTLOOKUPS> CONTACTLOOKUPS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTACTLOOKUPS> CONTACTLOOKUPS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTACTS> CONTACTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMAILGROUPS> EMAILGROUPS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMAILRECIPIENTS> EMAILRECIPIENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMAILRECIPIENTS> EMAILRECIPIENTS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMAILS> EMAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSPATTRIBS> INSPATTRIBS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSPCHAINOFCUSTODY> INSPCHAINOFCUSTODY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSPCHAINOFCUSTODY> INSPCHAINOFCUSTODY1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSPCHECKSHEET> INSPCHECKSHEET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSPCHECKSHEETATTRIBS> INSPCHECKSHEETATTRIBS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSPECTIONREQS> INSPECTIONREQS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSPECTIONREQS> INSPECTIONREQS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSPECTIONS> INSPECTIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSPECTIONS> INSPECTIONS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSPECTIONS> INSPECTIONS2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSPWORKFLOWS> INSPWORKFLOWS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSPWORKFLOWS> INSPWORKFLOWS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANCHAINOFCUSTODY> PLANCHAINOFCUSTODY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANREVIEWMETRICS> PLANREVIEWMETRICS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECTATTRIBLEVELS> PROJECTATTRIBLEVELS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECTATTRIBS> PROJECTATTRIBS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRIVINSPOBJS> PRIVINSPOBJS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANTRANSFERWORKFLOW> PLANTRANSFERWORKFLOW { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANCHAINOFCUSTODY> PLANCHAINOFCUSTODY1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJINSPTEMPLATE> PROJINSPTEMPLATE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJOOOINSPS> PROJOOOINSPS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECTATTRIBLEVELS> PROJECTATTRIBLEVELS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANSUBMITTALS> PLANSUBMITTALS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANTRANSFERWORKFLOW> PLANTRANSFERWORKFLOW1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANTRANSFERWORKFLOW> PLANTRANSFERWORKFLOW2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJMATERIALS> PROJMATERIALS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJMATERIALS> PROJMATERIALS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJMATERIALS> PROJMATERIALS2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJINSPASSETS> PROJINSPASSETS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECTS> PROJECTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJINSPINFO> PROJINSPINFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJINSPINFO> PROJINSPINFO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJINSPINFO> PROJINSPINFO2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJINSPINFO> PROJINSPINFO3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECTS> PROJECTS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECTS> PROJECTS2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJINSPINFO> PROJINSPINFO4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEGMENTS> SEGMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANSUBMITTALS> PLANSUBMITTALS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEGMENTS> SEGMENTS1 { get; set; }
    }
}
