//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PORTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManagerReportStaticData
    {
        public int id { get; set; }
        public string MetricName { get; set; }
        public string MetricYearMonth { get; set; }
        public Nullable<decimal> MetricValue { get; set; }
    }
}
