//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PORTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MANHOLES
    {
        public long MHID { get; set; }
        public Nullable<long> PROJECTID { get; set; }
        public string INTERNALNAME { get; set; }
        public string EXTERNALNAME { get; set; }
        public bool ACCEPTED { get; set; }
        public string ACCEPTED_BY { get; set; }
        public Nullable<System.DateTime> ACCEPTED_DT { get; set; }
        public string INTERNALID { get; set; }
        public Nullable<long> PARCELID { get; set; }
        public string BOOK { get; set; }
        public string SECTION { get; set; }
        public string SEQNUM { get; set; }
        public Nullable<double> RIM { get; set; }
        public Nullable<double> INV_IN1 { get; set; }
        public Nullable<double> INV_IN2 { get; set; }
        public Nullable<double> INV_IN3 { get; set; }
        public Nullable<double> INV_OUT { get; set; }
        public Nullable<double> NORTHING { get; set; }
        public Nullable<double> EASTING { get; set; }
        public Nullable<bool> IS_PUBLIC { get; set; }
        public bool EXISTING { get; set; }
        public Nullable<bool> SPECIAL { get; set; }
        public Nullable<System.DateTime> RECORD_DT { get; set; }
        public Nullable<long> MH_SIZE { get; set; }
        public bool PSOURCENOTINGIS { get; set; }
        public string PAGES { get; set; }
        public bool IS_ACTIVE { get; set; }
        public string ADDED_BY { get; set; }
        public System.DateTime ADDED_DT { get; set; }
        public string UPDATED_BY { get; set; }
        public System.DateTime UPDATED_DT { get; set; }
    }
}
