//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PORTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARCELS
    {
        public long ParcelID { get; set; }
        public long ProjectID { get; set; }
        public string ParcelNumber { get; set; }
        public bool IS_ACTIVE { get; set; }
        public string ADDED_BY { get; set; }
        public System.DateTime ADDED_DT { get; set; }
        public string UPDATED_BY { get; set; }
        public System.DateTime UPDATED_DT { get; set; }
        public bool LOCKED_FOR_EDIT { get; set; }
        public string LOCKED_BY { get; set; }
        public Nullable<System.DateTime> LOCKED_DT { get; set; }
    
        public virtual PROJECTS PROJECTS { get; set; }
    }
}
