//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PORTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLANSUBMITTALS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PLANSUBMITTALS()
        {
            this.CHECKSHEET = new HashSet<CHECKSHEET>();
            this.PLANCHAINOFCUSTODY = new HashSet<PLANCHAINOFCUSTODY>();
            this.PLANREVISIONS = new HashSet<PLANREVISIONS>();
        }
    
        public long PlanSubmittalID { get; set; }
        public long ProjectID { get; set; }
        public long SubmittalNumber { get; set; }
        public long SubmittalChildNumber { get; set; }
        public Nullable<long> SubmittalDispositionID { get; set; }
        public string TrackingCode { get; set; }
        public string Submitted_By { get; set; }
        public string Received_By { get; set; }
        public System.DateTime Received_DT { get; set; }
        public string ReceivedByOnBehalfOf { get; set; }
        public long MediaID { get; set; }
        public decimal MediaSubmittalNumber { get; set; }
        public long PlanSubmittalStatusID { get; set; }
        public Nullable<System.DateTime> CUSTOMER_NOTIFIED_DT { get; set; }
        public string CUSTOMER_NOTIFIED_BY { get; set; }
        public bool IS_ACTIVE { get; set; }
        public bool IS_ARCHIVED { get; set; }
        public string ADDED_BY { get; set; }
        public System.DateTime ADDED_DT { get; set; }
        public string UPDATED_BY { get; set; }
        public System.DateTime UPDATED_DT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHECKSHEET> CHECKSHEET { get; set; }
        public virtual LOOKUP LOOKUP { get; set; }
        public virtual LOOKUP LOOKUP1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANCHAINOFCUSTODY> PLANCHAINOFCUSTODY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANREVISIONS> PLANREVISIONS { get; set; }
        public virtual PROJECTS PROJECTS { get; set; }
    }
}
