//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PORTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLANREVISIONS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PLANREVISIONS()
        {
            this.PLANREVIEWMETRICS = new HashSet<PLANREVIEWMETRICS>();
        }
    
        public long PlanRevisionID { get; set; }
        public long ProjectID { get; set; }
        public long PlanSubmittalID { get; set; }
        public long PlanRevisionNumber { get; set; }
        public long CHKSHEETTEMPLNUM { get; set; }
        public Nullable<long> NumSheets { get; set; }
        public string BookPage { get; set; }
        public string SheetNum { get; set; }
        public string Evaluated_BY { get; set; }
        public Nullable<System.DateTime> EvaluateStart_DT { get; set; }
        public Nullable<System.DateTime> EvaluateEnd_DT { get; set; }
        public bool IS_ACTIVE { get; set; }
        public string ADDED_BY { get; set; }
        public System.DateTime ADDED_DT { get; set; }
        public string UPDATED_BY { get; set; }
        public System.DateTime UPDATED_DT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANREVIEWMETRICS> PLANREVIEWMETRICS { get; set; }
        public virtual PLANSUBMITTALS PLANSUBMITTALS { get; set; }
        public virtual PROJECTS PROJECTS { get; set; }
    }
}
