//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PORTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POCREQUEST
    {
        public long POCREQUESTID { get; set; }
        public Nullable<long> PROJECTID { get; set; }
        public string PROJECTDESC { get; set; }
        public string ParcelNumber { get; set; }
        public double ERU { get; set; }
        public double QAVG { get; set; }
        public long ContactID { get; set; }
        public string REQUEST_BY { get; set; }
        public System.DateTime REQUEST_DT { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> PROCESS_DT { get; set; }
        public Nullable<System.DateTime> ISSUE_DT { get; set; }
        public Nullable<System.DateTime> EXPIRATION_DT { get; set; }
        public string POC_REQ_TRK_NUM { get; set; }
        public bool IS_ACTIVE { get; set; }
        public string ADDED_BY { get; set; }
        public System.DateTime ADDED_DT { get; set; }
        public string UPDATED_BY { get; set; }
        public System.DateTime UPDATED_DT { get; set; }
    
        public virtual CONTACTS CONTACTS { get; set; }
    }
}
