//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PORTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJINSPASSETS
    {
        public long PROJINSPASSETID { get; set; }
        public long PROJECTID { get; set; }
        public long ASSETTYPEID { get; set; }
        public string ASSETNAME { get; set; }
        public string UPMHNAME { get; set; }
        public string DNMHNAME { get; set; }
        public bool IS_POC { get; set; }
        public bool IS_STUB { get; set; }
        public bool ADDED_POST_APPROVAL { get; set; }
        public bool IS_EXTERNAL_TO_PROJECT { get; set; }
        public bool IS_ACTIVE { get; set; }
        public string ADDED_BY { get; set; }
        public System.DateTime ADDED_DT { get; set; }
        public string UPDATED_BY { get; set; }
        public System.DateTime UPDATED_DT { get; set; }
    
        public virtual LOOKUP LOOKUP { get; set; }
        public virtual PROJECTS PROJECTS { get; set; }
    }
}
