//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PORTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROJECTS()
        {
            this.ASSETATTRIBS = new HashSet<ASSETATTRIBS>();
            this.CERTSOFOCC = new HashSet<CERTSOFOCC>();
            this.EMAILS = new HashSet<EMAILS>();
            this.INSPECTIONREQS = new HashSet<INSPECTIONREQS>();
            this.PARCELS = new HashSet<PARCELS>();
            this.PLANREVIEWMETRICS = new HashSet<PLANREVIEWMETRICS>();
            this.PLANREVISIONS = new HashSet<PLANREVISIONS>();
            this.PLANSUBMITTALS = new HashSet<PLANSUBMITTALS>();
            this.PRIVINSPOBJS = new HashSet<PRIVINSPOBJS>();
            this.PROJCOMPANIES = new HashSet<PROJCOMPANIES>();
            this.PROJCONTACTS = new HashSet<PROJCONTACTS>();
            this.PROJECTATTRIBS = new HashSet<PROJECTATTRIBS>();
            this.PROJECTPHASES = new HashSet<PROJECTPHASES>();
            this.PROJINSPASSETS = new HashSet<PROJINSPASSETS>();
            this.PROJINSPINFO = new HashSet<PROJINSPINFO>();
            this.PROJINSPTEMPLATE = new HashSet<PROJINSPTEMPLATE>();
            this.PROJMATERIALS = new HashSet<PROJMATERIALS>();
            this.PROJOOOINSPS = new HashSet<PROJOOOINSPS>();
            this.PROJPOCS = new HashSet<PROJPOCS>();
            this.SEGMENTS = new HashSet<SEGMENTS>();
        }
    
        public long PROJECTID { get; set; }
        public bool IS_VALID { get; set; }
        public Nullable<long> PROJYEAR { get; set; }
        public Nullable<long> PROJNUMSEQ { get; set; }
        public string PROJECTNUMBER { get; set; }
        public string PROJECTNAME { get; set; }
        public string FKA { get; set; }
        public long PROJECTSTATUSID { get; set; }
        public Nullable<long> PREV_PROJECTSTATUSID { get; set; }
        public Nullable<long> PROJECTTYPEID { get; set; }
        public Nullable<long> PROJECTCLASSID { get; set; }
        public bool PLANSREQUIRED { get; set; }
        public string NSCROSSSTREETS { get; set; }
        public string EWCROSSSTREETS { get; set; }
        public bool COUNTYPERMITREQ { get; set; }
        public bool COUNTYPERMITAPPROVED { get; set; }
        public bool ILA { get; set; }
        public Nullable<System.DateTime> ILA_APPROVAL_DT { get; set; }
        public bool JOBSTART { get; set; }
        public Nullable<System.DateTime> JOBSTARTDATE { get; set; }
        public Nullable<System.DateTime> BOND_DT { get; set; }
        public Nullable<bool> NA_BOND { get; set; }
        public string BOND_BY { get; set; }
        public Nullable<System.DateTime> ASBUILT_DT { get; set; }
        public Nullable<bool> NA_RECORD { get; set; }
        public string RECORD_BY { get; set; }
        public string FINAL_INSPECTOR { get; set; }
        public Nullable<System.DateTime> FINAL_DT { get; set; }
        public string BOND_REL_INSPECTOR { get; set; }
        public Nullable<System.DateTime> BOND_REL_DT { get; set; }
        public bool OVERSIZE { get; set; }
        public Nullable<decimal> OVERSIZECOST { get; set; }
        public Nullable<System.DateTime> OVERSIZEBOARDAPPROVALDATE { get; set; }
        public string REFUND_NUMBER { get; set; }
        public Nullable<System.DateTime> REFUND_DT { get; set; }
        public string LIFTSTATIONNUM { get; set; }
        public bool MHADJUST { get; set; }
        public string DEVELOPERPROJNUM { get; set; }
        public string PROCTOR { get; set; }
        public bool IS_ACTIVE { get; set; }
        public string ADDED_BY { get; set; }
        public System.DateTime ADDED_DT { get; set; }
        public string UPDATED_BY { get; set; }
        public System.DateTime UPDATED_DT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSETATTRIBS> ASSETATTRIBS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CERTSOFOCC> CERTSOFOCC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMAILS> EMAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSPECTIONREQS> INSPECTIONREQS { get; set; }
        public virtual LOOKUP LOOKUP { get; set; }
        public virtual LOOKUP LOOKUP1 { get; set; }
        public virtual LOOKUP LOOKUP2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARCELS> PARCELS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANREVIEWMETRICS> PLANREVIEWMETRICS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANREVISIONS> PLANREVISIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANSUBMITTALS> PLANSUBMITTALS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRIVINSPOBJS> PRIVINSPOBJS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJCOMPANIES> PROJCOMPANIES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJCONTACTS> PROJCONTACTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECTATTRIBS> PROJECTATTRIBS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECTPHASES> PROJECTPHASES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJINSPASSETS> PROJINSPASSETS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJINSPINFO> PROJINSPINFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJINSPTEMPLATE> PROJINSPTEMPLATE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJMATERIALS> PROJMATERIALS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJOOOINSPS> PROJOOOINSPS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJPOCS> PROJPOCS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEGMENTS> SEGMENTS { get; set; }
    }
}
