//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PORTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJPOCS
    {
        public long PROJPOCID { get; set; }
        public long PROJECTID { get; set; }
        public long OBJECTID { get; set; }
        public string MHNO { get; set; }
        public Nullable<long> INVNUM { get; set; }
        public string PTYPE { get; set; }
        public string SOURCE { get; set; }
        public Nullable<System.DateTime> STATUSDATE { get; set; }
        public string STATUS { get; set; }
        public bool IS_STUB { get; set; }
        public bool IS_ACTIVE { get; set; }
        public string ADDED_BY { get; set; }
        public System.DateTime ADDED_DT { get; set; }
        public string UPDATED_BY { get; set; }
        public System.DateTime UPDATED_DT { get; set; }
    
        public virtual PROJECTS PROJECTS { get; set; }
    }
}
