//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PORTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJMATERIALS
    {
        public long projmaterialID { get; set; }
        public long projectID { get; set; }
        public long pmsizeid { get; set; }
        public long pmtypeid { get; set; }
        public long pmunitid { get; set; }
        public decimal pmamount { get; set; }
        public bool IS_ACTIVE { get; set; }
        public string ADDED_BY { get; set; }
        public System.DateTime ADDED_DT { get; set; }
        public string UPDATED_BY { get; set; }
        public System.DateTime UPDATED_DT { get; set; }
    
        public virtual LOOKUP LOOKUP { get; set; }
        public virtual LOOKUP LOOKUP1 { get; set; }
        public virtual LOOKUP LOOKUP2 { get; set; }
        public virtual PROJECTS PROJECTS { get; set; }
    }
}
