//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PORTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECTPHASES
    {
        public long PROJECTPHASEID { get; set; }
        public long PROJECTID { get; set; }
        public string PHASE { get; set; }
        public string HTE { get; set; }
        public long PHASESTATUSID { get; set; }
        public bool IS_ACTIVE { get; set; }
        public bool HAS_ASSETS { get; set; }
        public Nullable<bool> ASSETS_ACCEPTED { get; set; }
        public Nullable<System.DateTime> ASSETS_ACCEPTED_DT { get; set; }
        public string ADDED_BY { get; set; }
        public System.DateTime ADDED_DT { get; set; }
        public string UPDATED_BY { get; set; }
        public System.DateTime UPDATED_DT { get; set; }
    
        public virtual PROJECTS PROJECTS { get; set; }
    }
}
