//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PORTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJCONTACTS
    {
        public long ProjContactID { get; set; }
        public long ProjectID { get; set; }
        public long ContactID { get; set; }
        public Nullable<long> ContactTypeID { get; set; }
        public bool IS_ACTIVE { get; set; }
        public string ADDED_BY { get; set; }
        public System.DateTime ADDED_DT { get; set; }
        public string UPDATED_BY { get; set; }
        public System.DateTime UPDATED_DT { get; set; }
    
        public virtual CONTACTS CONTACTS { get; set; }
        public virtual PROJECTS PROJECTS { get; set; }
    }
}
