//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PORTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRREQUEST
    {
        public long PRREQUESTID { get; set; }
        public string PROJECTNUMBER { get; set; }
        public string PROJECTNAME { get; set; }
        public string PDFFILE { get; set; }
        public string REQUEST_BY { get; set; }
        public System.DateTime REQUEST_DT { get; set; }
    }
}
