//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PORTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSGRAVITYMAIN
    {
        public int OBJECTID { get; set; }
        public string OWNERSHIP { get; set; }
        public string SOURCE { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public string STATUS { get; set; }
        public string SWNO { get; set; }
        public string UPMH { get; set; }
        public string DNMH { get; set; }
        public string MATERIAL { get; set; }
        public Nullable<decimal> DIAMETER { get; set; }
        public Nullable<decimal> DESIGNLENGTH { get; set; }
    }
}
