//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PORTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPLOADEDDOCS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UPLOADEDDOCS()
        {
            this.ATTACHMENTS = new HashSet<ATTACHMENTS>();
        }
    
        public long UPLOADEDDOCID { get; set; }
        public long PROJID { get; set; }
        public string FILE_NAME { get; set; }
        public string FILE_LOCATION { get; set; }
        public string FILE_DESCRIPTION { get; set; }
        public string NW_PATH { get; set; }
        public Nullable<long> FILE_LENGTH { get; set; }
        public Nullable<System.DateTime> FILE_CREATE_DT { get; set; }
        public long OWNERTYPEID { get; set; }
        public long RECORDID { get; set; }
        public bool IS_ACTIVE { get; set; }
        public string ADDED_BY { get; set; }
        public System.DateTime ADDED_DT { get; set; }
        public string UPDATED_BY { get; set; }
        public System.DateTime UPDATED_DT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATTACHMENTS> ATTACHMENTS { get; set; }
    }
}
