//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PORTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAboutItems_ALL
    {
        public string ver_no { get; set; }
        public System.DateTime version_added_dt { get; set; }
        public string version_added_by { get; set; }
        public string HIGHLIGHT { get; set; }
        public System.DateTime highlight_added_dt { get; set; }
        public string highlight_added_by { get; set; }
        public bool version_active { get; set; }
        public bool highlight_active { get; set; }
        public long version_id { get; set; }
        public long highlight_id { get; set; }
    }
}
