//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PORTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAboutItems_ACTIVE
    {
        public string ver_no { get; set; }
        public System.DateTime version_added { get; set; }
        public string HIGHLIGHT { get; set; }
        public System.DateTime highlight_added { get; set; }
    }
}
