//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PORTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwSegmentInfo
    {
        public long SEGMENTID { get; set; }
        public long PHASEID { get; set; }
        public string UpInternalName { get; set; }
        public string UpExternalName { get; set; }
        public string DownInternalName { get; set; }
        public string DownExternalName { get; set; }
        public string SizeDescription { get; set; }
        public string TypeDescription { get; set; }
        public Nullable<long> LENGTH { get; set; }
        public bool IS_ACTIVE { get; set; }
        public string ADDED_BY { get; set; }
        public System.DateTime ADDED_DT { get; set; }
        public string UPDATED_BY { get; set; }
        public System.DateTime UPDATED_DT { get; set; }
    }
}
